### ISSUE TITLE
XState: Open Inspector from command palette doesn’t auto update

### ISSUE THREAD

**Issue by quasor** [mattpocock/xstate-vscode#15]
1. Launch the inspector from the command palette (not the Open Inspector link in the editor).
2. Observe edits made to the machine aren’t reflected in the inspector.

**Comment by mattpocock** [comment]
Fixed in 1.1.15

**Comment by tomByrer** [comment]
Unfortunately edits are not updating the inspector for me in v1.4.1 @mattpocock

**Comment by mattpocock** [comment]
@tomByrer Could you provide a repro piece of code where this happens? What are your repro steps?
