### ISSUE TITLE
Casting MachineConfig breaks the inspector

### ISSUE THREAD

**Issue by mdpratt** [mattpocock/xstate-vscode#16]
**User story:**
When I inline cast my machine's config, I expect the extension to behave as normal.

**Expected behaviour:**
* `Open inspector` prompt appears.
* If the inspector is open, it should update.

**Actual:**
* `Open inspector` prompt is not visible.
* If the inspector is open, it stops updating.

**Steps to reproduce:**
```typescript
const myModel = createModel({});

export type MyContext = ContextFrom<typeof myModel >;
export type MyEvent = EventFrom<typeof myModel>;

type MyConfig = MachineConfig<MyContext , any, MyEvent >;

// Either of these break
myModel.createMachine({ id: "HelloWorld" } as MyConfig);
myModel.createMachine(<MyConfig>{ id: "HelloWorld" });

// This works
const myConfig: MyConfig = { id: "HelloWorld" };
myModel.createMachine(myConfig);
```

**Comment by mattpocock** [comment]
Fixed in 1.1.14
