### ISSUE TITLE
Feature request: capability to pan the machine in the visualizer

### ISSUE THREAD

**Issue by shichen85** [mattpocock/xstate-vscode#25]
![img](https://i.imgur.com/9qGSovr.png)

Hello, in https://stately.ai/viz, you can pan the visualized machine with the hand button as shown above. However, in the VSCode visualizer, there is no such button. If the visualized machine is very long, we either have to zoom out very far and not be able to read the text, or we will have to zoom in and not be able to see parts of the machine. 

Is it possible to implement a panning capability? 

Thank you.

**Comment by mattpocock** [comment]
@shichen85 Sure, you can use the space bar and pan the screen.

**Comment by grahamb** [comment]
Is this documented anywhere? It's not very discoverable; I only learned about it from this issue. I was about to open a similar one. 😄

**Comment by zzestio** [comment]
Came here to suggest panning in the VSCode extension. Not very usable on small screens or large machines. Great tip about the spacebar! A hand icon will definitely help, even if it just tells you to use space.
